language: android
sudo: false
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew check
  - ./gradlew detekt
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)